-- Generated by scripts/upload_disease_images_and_generate_sql.sh
-- DO_UPLOAD=true
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB6A4EC9691EC84B120EAB081EBA789ECA788ED9998' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB6A4EC9691EC84B120EAB081EBA789ECA788ED9998' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB6A4EC9691EC84B120EAB081EBA789ECA788ED9998' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB6A4EC9691EC84B120EAB081EBA789ECA788ED9998' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC8389EC868CECB9A8ECB0A9EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC8389EC868CECB9A8ECB0A9EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC8389EC868CECB9A8ECB0A9EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC8389EC868CECB9A8ECB0A9EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EB82B4EBB098ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EB82B4EBB098ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EB82B4EBB098ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EB82B4EBB098ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280ECA285EC9691' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280ECA285EC9691' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280ECA285EC9691' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280ECA285EC9691' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9CA0EBA3A8ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9CA0EBA3A8ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9CA0EBA3A8ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9CA0EBA3A8ECA69D' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'ED95B5EAB2BDED9994' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'ED95B5EAB2BDED9994' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'ED95B5EAB2BDED9994' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'ED95B5EAB2BDED9994' USING utf8mb4), 'DOG', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EAB6A4EC9691' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EAB6A4EC9691' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EAB6A4EC9691' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EAB6A4EC9691' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EBB680EAB3A8ED8EB8' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EBB680EAB3A8ED8EB8' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EBB680EAB3A8ED8EB8' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB081EBA789EBB680EAB3A8ED8EB8' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'main' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'main' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'main' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'main' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EAB2B0EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EBB984EAB6A4EC9691EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EBB984EAB6A4EC9691EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EBB984EAB6A4EC9691EC84B1EAB081EBA789EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'danger' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'danger' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'danger' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'danger' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'caution' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'caution' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'caution' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'caution' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg' ELSE danger_example_image_url END;
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES (CONVERT(X'EC9588EAB280EC97BC' USING utf8mb4), 'CAT', 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg', NULL, NULL, NULL, CONVERT(X'EBAFB8EBB684EBA598' USING utf8mb4), '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN 'mild' = 'main' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN 'mild' = 'mild' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN 'mild' = 'caution' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN 'mild' = 'danger' THEN 'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg' ELSE danger_example_image_url END;
