SET NAMES utf8mb4;

INSERT INTO diseases
(disease_name, species, category, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, symptoms, description, care_guide)
VALUES
('안검염','DOG','눈꺼풀질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검염/danger.jpg',
'','', ''),
('안검종양','DOG','눈꺼풀질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검종양/danger.jpg',
'','', ''),
('안검내반증','DOG','눈꺼풀질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/안검내반증/danger.jpg',
'','', ''),
('유루증','DOG','눈물계질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/유루증/danger.jpg',
'','', ''),
('색소침착성각막염','DOG','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/색소침착성각막염/danger.jpg',
'','', ''),
('핵경화','DOG','수정체질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/핵경화/danger.jpg',
'','', ''),
('궤양성 각막질환','DOG','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/궤양성 각막질환/danger.jpg',
'','', ''),
('비궤양성 각막질환','DOG','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/비궤양성 각막질환/main.png',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/비궤양성 각막질환/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/비궤양성 각막질환/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/비궤양성 각막질환/danger.jpg',
'','', ''),
('결막염','DOG','결막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/DOG/결막염/danger.jpg',
'','', ''),
('결막염','CAT','결막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/main.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/결막염/danger.jpg',
'','', ''),
('안검염','CAT','눈꺼풀질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/안검염/danger.jpg',
'','', ''),
('각막궤양','CAT','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/main.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막궤양/danger.jpg',
'','', ''),
('각막부골편','CAT','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/main.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/각막부골편/danger.jpg',
'','', ''),
('비궤양성각막염','CAT','각막질환',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/mild.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/caution.jpg',
'https://YOUR_S3_BUCKET_NAME.s3.ap-northeast-2.amazonaws.com/uploads/diseases/CAT/비궤양성각막염/danger.jpg',
'','', '')
ON DUPLICATE KEY UPDATE
category = VALUES(category),
disease_image_url = VALUES(disease_image_url),
mild_example_image_url = VALUES(mild_example_image_url),
caution_example_image_url = VALUES(caution_example_image_url),
danger_example_image_url = VALUES(danger_example_image_url);
