#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="${1:?base image directory required as \$1, e.g. ./중증도별 분류 사진}"
OUT_SQL="${2:-scripts/disease_images_upsert.sql}"
DO_UPLOAD="${DO_UPLOAD:-true}"

BUCKET="${AWS_S3_BUCKET:?set AWS_S3_BUCKET env var}"
REGION="${AWS_REGION:-ap-northeast-2}"
PREFIX="${S3_PREFIX:-uploads/diseases}"
PUBLIC_BASE_URL="${AWS_S3_PUBLIC_BASE_URL:-https://${BUCKET}.s3.${REGION}.amazonaws.com}"

if [[ ! -d "$BASE_DIR" ]]; then
  echo "Base directory not found: $BASE_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_SQL")"

cat > "$OUT_SQL" <<SQL
-- Generated by scripts/upload_disease_images_and_generate_sql.sh
-- DO_UPLOAD=$DO_UPLOAD
SQL

normalize_species() {
  local s="$1"
  case "$s" in
    강아지) echo "DOG" ;;
    고양이) echo "CAT" ;;
    *) echo "" ;;
  esac
}

map_stage() {
  local f="$1"
  case "$f" in
    무) echo "main" ;;
    하) echo "mild" ;;
    중) echo "caution" ;;
    상) echo "danger" ;;
    main|mild|caution|danger) echo "$f" ;;
    *) echo "" ;;
  esac
}

escape_sql() {
  echo "$1" | sed "s/'/''/g"
}

to_utf8mb4_expr() {
  local value="$1"
  local hex
  hex=$(printf '%s' "$value" | xxd -p -u | tr -d '\n')
  printf "CONVERT(X'%s' USING utf8mb4)" "$hex"
}

find "$BASE_DIR" -mindepth 3 -maxdepth 3 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) | sort | while IFS= read -r file; do
  species_kr=$(basename "$(dirname "$(dirname "$file")")")
  disease_name=$(basename "$(dirname "$file")")
  filename=$(basename "$file")
  stem="${filename%.*}"

  species=$(normalize_species "$species_kr")
  stage=$(map_stage "$stem")

  if [[ -z "$species" || -z "$stage" ]]; then
    continue
  fi

  key="$PREFIX/$species/$disease_name/$stage.jpg"
  url="$PUBLIC_BASE_URL/$key"

  if [[ "$DO_UPLOAD" == "true" ]]; then
    aws s3 cp "$file" "s3://$BUCKET/$key" --region "$REGION" >/dev/null
  fi

  e_name_expr=$(to_utf8mb4_expr "$disease_name")
  e_category_expr=$(to_utf8mb4_expr "미분류")
  e_url=$(escape_sql "$url")

  cat >> "$OUT_SQL" <<SQL
INSERT INTO diseases (disease_name, species, disease_image_url, mild_example_image_url, caution_example_image_url, danger_example_image_url, category, description, symptoms, care_guide)
VALUES ($e_name_expr, '$species', '$e_url', NULL, NULL, NULL, $e_category_expr, '', '', '')
ON DUPLICATE KEY UPDATE
  disease_image_url = CASE WHEN '$stage' = 'main' THEN '$e_url' ELSE disease_image_url END,
  mild_example_image_url = CASE WHEN '$stage' = 'mild' THEN '$e_url' ELSE mild_example_image_url END,
  caution_example_image_url = CASE WHEN '$stage' = 'caution' THEN '$e_url' ELSE caution_example_image_url END,
  danger_example_image_url = CASE WHEN '$stage' = 'danger' THEN '$e_url' ELSE danger_example_image_url END;
SQL

done

echo "Done. SQL written to: $OUT_SQL"
